services:
  postgres:
    image: postgres:15
    container_name: easy_apply_db
    environment:
      - POSTGRES_USER=easyapply
      - POSTGRES_PASSWORD=easyapplypassword
      - POSTGRES_DB=easyapplydb
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U easyapply"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: